### ISSUE TITLE
standalone GML repo

### ISSUE THREAD

**Issue by shaunlebron** [jystic/vim#2]
Hi, thanks for making the GML syntax file for vim!

wondering if you're interested in creating a separate repo like 'vim-gml' with the following files:

```
- syntax/gml.vim
- ftdetect/gml.vim  (autocmd BufNewFile,BufRead *.gml set filetype=gml)
```

would make it easier for others to use via Vundle.

**Comment by jystic** [comment]
Yeah I don't mind doing that, although I'm a little confused, do you work for Fugro?

I didn't expect there would be much demand for a GML syntax plugin haha :smile:

**Comment by shaunlebron** [comment]
well, this is awkward.  I looked up Fugro (actually have a location in houston), and realized that your syntax file is not for Game Maker Language, lol.  Apparently, it had enough in common to fool me.  nevermind!

**Comment by jystic** [comment]
Haha :laughing: I even looked up your location on Github (Houston) and thought, hmmm it's plausible that you might work for them :smile: 

fwiw GML is a scripting language for processing gps/gyro/accelerometer/multibeam data
